TTS.Web/Controllers/JobController.cs
using System;
using System.Linq;
using System.Threading.Tasks;
using AutoMapper;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity.UI.Services;
using Microsoft.AspNetCore.Mvc;
using TTS.BLL.Services.Abstract;
using TTS.DAL;
using TTS.Shared.Models.Job;
using TTS.Shared.Models.Status;
using TTS.Shared.Models.Todo;
using TTS.Shared.Models.User;

namespace TTS.Web.Controllers
{
    [Authorize]
    public class JobController : Controller
    {
        private readonly IJobService _jobService;
        private readonly IUserService _userService;
        private readonly IMapper _mapper;
        private readonly IStatusService _statusService;
        private readonly IEmployeeService _employeeService;
        
        public JobController(IJobService jobService, IUserService userService, IMapper mapper, IStatusService statusService, IEmployeeService employeeService, IEmailSender emailSender)
        {
            _jobService = jobService;
            _userService = userService;
            _mapper = mapper;
            _statusService = statusService;
            _employeeService = employeeService;
        }

        public async Task<IActionResult> Index()
        {
            var result = await _jobService.GetByUser<JobDto>(HttpContext.User);
            //TODO ensure OK
            var jobs = result.Value;
            foreach (var job in jobs)
            {
                var status = await _statusService.GetAsync<StatusDto>(job.StatusId);
                job.Status = status.Value;
            }
            var models = jobs;
            return View(models);
        }

        [HttpGet]
        public async Task<IActionResult> Details(Guid? id)
        {
            if (id == null) return BadRequest();
            var result = await _jobService.GetAsync<JobDetailsDto>((Guid) id);
            //TODO Ensure ok
            var job = result.Value;
            var status = await _statusService.GetAsync<StatusDto>(job.StatusId);
            job.Status = status.Value;
            var users = await _userService.GetByJobAsync<UserDto>(job.Id);
            job.Users = users.Value.ToList();
            var model = job;
            return View(model);
        }

        public async Task<IActionResult> Create()
        {
            var user = await _userService.GetAsync<UserDto>(HttpContext.User);
            var users = await _employeeService.GetAsync<UserDto>(user.Value.Id);
            var statuses = await _statusService.GetAllAsync<StatusDto>();
            ViewBag.Statuses = statuses.Value;
            ViewBag.Users = users.Value;
            return View(new JobCreateDto());
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(JobCreateDto dto)
        {
            if (!ModelState.IsValid) return View(dto);
            var job = await _jobService.CreateAsync(dto);
            //TODO ensure ok
            return RedirectToAction(nameof(Index));
        }

        
        public async Task<IActionResult> Edit(Guid? id)
        {
            if (id == null) return BadRequest();
            var job = await _jobService.GetAsync<JobEditDto>((Guid) id);
            //TODO ensure ok
            var model = job.Value;
            var users = await _userService.GetByJobAsync<UserDto>(model.Id);
            var statuses = await _statusService.GetAllAsync<StatusDto>();
            ViewBag.Statuses = statuses.Value;
            ViewBag.Users = users.Value;
            return View(model);
        }
        
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(JobEditDto dto)
        {
            if (!ModelState.IsValid) return View(dto);
            var result = await _jobService.UpdateAsync(dto); 
            //TODO Ensure OK
            
            return RedirectToAction(nameof(Index));
        }

        
        [HttpGet,Authorize(Roles = "admin")]
        public async Task<IActionResult> Delete(Guid? id)
        {
            if (id == null) return BadRequest();

            var result = await _jobService.GetAsync<JobDto>((Guid) id);
            //TODO ensure ok
            var model = result.Value;
            return View(model);
        }

        
        [HttpPost, ActionName("Delete"),Authorize(Roles = "admin")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(Guid id)
        {
            var result = await _jobService.DeleteByIdAsync<JobDto>(id);
            //TODO Ensure ok
            return RedirectToAction(nameof(Index));
        }

        
    }
}

TTS.Web/Controllers/RoleController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using AutoMapper;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.ModelBinding;
using Microsoft.AspNetCore.Mvc.Rendering;
using TTS.BLL;
using TTS.BLL.Services;
using TTS.BLL.Services.Abstract;
using TTS.Shared.Models.User;
using TTS.Shared.Models.Role;

namespace TTS.Web.Controllers
{
    [Authorize(Roles = "admin")]
    public class RoleController : Controller
    {
        private readonly IRoleService _roleService;
        private readonly IUserService _userService;
        
        public RoleController(IRoleService roleService, IUserService userService)
        {
            _roleService = roleService;
            _userService = userService;
        }

        public async Task<IActionResult> Index()
        {
            var result = await _roleService.GetAllAsync<RoleDto>();
            //TODO ensure ok
            var models = result.Value;
            return View(models);
        }
        
        public IActionResult Create() => View();

        [HttpPost]
        public async Task<IActionResult> Create(RoleDto dto)
        {
            if (!ModelState.IsValid) return View(dto.Name);
            var result = await _roleService.CreateAsync(dto);
            //TODO Ensure OK
            return Redirect(nameof(Index));
        }

        [HttpGet]
        public async Task<IActionResult> Edit(Guid? id)
        {
            if (id == null) return BadRequest();
            var result = await _roleService.GetAsync<RoleDto>((Guid)id);
            //TODO ensure ok
            var model = result.Value;
            return View(model);
        }
        
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(RoleDto dto)
        {
            if (!ModelState.IsValid) return View(dto);
            var result = await _roleService.UpdateAsync(dto);
            //TODO Ensure ok
            return RedirectToAction(nameof(Index));
        }

        [HttpGet]
        public async Task<IActionResult> Remove(Guid? id)
        {
            if (id == null) return BadRequest();
            var userRoles = await _roleService.GetByUserAsync((Guid)id);
            //TODO Ensure ok
            var model = new RoleRemoveDto()
            {
                UserId = (Guid)id
            };
            ViewBag.Roles = userRoles.Value;
            return View(model);
        }

        [HttpPost,ValidateAntiForgeryToken]
        public async Task<IActionResult> Remove(Guid id, RoleRemoveDto dto)
        {
            var result = await _roleService.RemoveRolesAsync(dto);
            //Ensure ok
            return RedirectToAction("Index","User");
        }
        
        [HttpGet]
        public async Task<IActionResult> Assign(Guid? id)
        {
            if (id == null) return BadRequest();
            var userRoles = await _roleService.GetByUserAsync((Guid)id);
            var allRoles = await _roleService.GetAllAsync<RoleDto>();
            //TODO Ensure ok
            var model = new RoleAssignDto()
            {
                UserId = (Guid)id,
                Roles = allRoles.Value.Select(x => x.Name).Except(userRoles.Value).ToList(),
                UserRoles = userRoles.Value.ToList()
            };
            return View(model);
        }

        [HttpPost,ValidateAntiForgeryToken]
        public async Task<IActionResult> Assign(Guid id, RoleAssignDto dto)
        {
            var result = await _roleService.AssignRolesAsync(dto);
            //Ensure ok
            return RedirectToAction("Index","User");
        }

        [HttpGet]
        public async Task<IActionResult> Delete(Guid? id)
        {
            if (id == null) return BadRequest();
            var result = await _roleService.GetAsync<RoleDto>((Guid)id);
            //TODO ensure ok
            var model = result.Value;
            return View(model);
        }


        [HttpPost, ActionName("Delete"),ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(Guid id)
        {
            var result = await _roleService.DeleteByIdAsync<RoleDto>(id);
            //TODO Ensure OK
            return RedirectToAction("Index");
        }
    }
}

TTS.Web/Controllers/StatusController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using TTS.BLL.Services.Abstract;
using TTS.DAL;
using TTS.DAL.Entities;
using TTS.Shared.Models.Status;

namespace TTS.Web
{
    [Authorize(Roles = "admin")]
    public class StatusController : Controller
    {
        private readonly IStatusService _statusService;

        public StatusController(IStatusService statusService)
        {
            _statusService = statusService;
        }

        
        public async Task<IActionResult> Index()
        {
            var result = await _statusService.GetAllAsync<StatusDto>();
            //TODO ensure OK
            var models = result.Value;
            return View(models);
        }


        public IActionResult Create()
        {
            return View();
        }

       
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(StatusDto dto)
        {
            if (ModelState == null || !ModelState.IsValid) return View(dto);
            var result = await _statusService.CreateAsync(dto);
            //TODO Ensure OK
            return RedirectToAction(nameof(Index));
        }

        
        public async Task<IActionResult> Edit(Guid? id)
        {
            if (id == null) return BadRequest();
            var result = await _statusService.GetAsync<StatusDto>((Guid)id);
            //TODO ensure ok
            var model = result.Value;
            return View(model);
        }
        
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(Guid id,StatusDto dto)
        {
            if (!ModelState.IsValid) return View(dto);
            var result = await _statusService.UpdateAsync(dto);
            //TODO Ensure ok
            return RedirectToAction(nameof(Index));
        }

        
        public async Task<IActionResult> Delete(Guid? id)
        {
            if (id == null) return BadRequest();
            var result = await _statusService.GetAsync<StatusDto>((Guid)id);
            //TODO ensure ok
            var model = result.Value;
            return View(model);
        }

        
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(Guid id)
        {
            var result = await _statusService.DeleteByIdAsync<StatusDto>(id);
            //TODO Ensure OK
            return RedirectToAction("Index");
        }

        
    }
}

TTS.Web/Views/Shared/_Layout.cshtml
@using Syncfusion.EJ2
@{
    const string ADMIN_ROLE = "admin";
}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - TTS.Web</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
    <link rel="stylesheet" href="https://cdn.syncfusion.com/ej2/bootstrap4.css" />
    <script src="https://cdn.syncfusion.com/ej2/dist/ej2.min.js"></script>
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">TTS.Web</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <partial name="_LoginPartial" />
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                         @if(User.IsInRole(ADMIN_ROLE)){
                             <li class="nav-item">
                                 <a class="nav-link text-dark" id="statuses" asp-controller="Status" asp-action="Index">Statuses</a>
                             </li>
                             <li class="nav-item">
                                 <a class="nav-link text-dark" id="users" asp-controller="User" asp-action="Index">Users</a>
                             </li>
                             <li class="nav-item">
                                 <a class="nav-link text-dark" id="roles" asp-controller="Role" asp-action="Index">Roles</a>
                             </li>
                         }
                        <li class="nav-item">
                            <a class="nav-link text-dark" id="jobs" asp-controller="Job" asp-action="Index">Jobs</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
<div class="container">
    <main role="main" class="pb-3">
        @RenderBody()
    </main>
</div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2020 - TTS.Web - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    <ejs-scripts></ejs-scripts>
    @RenderSection("Scripts", required: false)
</body>
</html>