TTS.Web/Controllers/EmployeeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using AutoMapper;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using TTS.BLL;
using TTS.BLL.Services;
using TTS.BLL.Services.Abstract;
using TTS.Shared.Models.Employee;
using TTS.Shared.Models.User;

namespace TTS.Web.Controllers
{
    [Authorize(Roles = "admin")]
    public class EmployeeController : Controller
    {
        private readonly IUserService _userService;
        private readonly IEmployeeService _employeeService;
        private readonly IMapper _mapper;

        public EmployeeController(IUserService userService, IMapper mapper, IEmployeeService employeeService)
        {
            _userService = userService;
            _mapper = mapper;
            _employeeService = employeeService;
        }

        [HttpGet]
        public async Task<IActionResult> Add(Guid id)
        {
            var employees = await _employeeService.GetAsync<UserDto>(id);
            var users = await _userService.GetAllAsync<UserDto>();
            var user = await _userService.GetAsync<UserDto>(id);
            //TODO Ensure OK
            employees.Value = employees.Value.Append(user.Value);
            var viewUsers = users.Value.Except(employees.Value);
            var model = new EmployeeDto()
            {
                Employees = viewUsers.ToList()
            };
            return View(model);
        }
        
        [HttpPost]
        public async Task<IActionResult> Add(Guid id, EmployeeDto dto)
        {
            if (!ModelState.IsValid) return View(dto);
            dto.UserId = id;
            await _employeeService.CreateAsync(dto);
            //TODO ensure ok
            return RedirectToAction("Index","User");
        }
    }
}

TTS.Web/Controllers/RoleController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using AutoMapper;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.ModelBinding;
using Microsoft.AspNetCore.Mvc.Rendering;
using TTS.BLL;
using TTS.BLL.Services;
using TTS.BLL.Services.Abstract;
using TTS.Shared.Models.User;
using TTS.Shared.Models.Role;

namespace TTS.Web.Controllers
{
    [Authorize(Roles = "admin")]
    public class RoleController : Controller
    {
        private readonly IRoleService _roleService;
        private readonly IUserService _userService;
        
        public RoleController(IRoleService roleService, IUserService userService)
        {
            _roleService = roleService;
            _userService = userService;
        }

        public async Task<IActionResult> Index()
        {
            var result = await _roleService.GetAllAsync<RoleDto>();
            //TODO ensure ok
            var models = result.Value;
            return View(models);
        }
        
        public IActionResult Create() => View();

        [HttpPost]
        public async Task<IActionResult> Create(RoleDto dto)
        {
            if (!ModelState.IsValid) return View(dto.Name);
            var result = await _roleService.CreateAsync(dto);
            //TODO Ensure OK
            return Redirect(nameof(Index));
        }

        [HttpGet]
        public async Task<IActionResult> Edit(Guid? id)
        {
            if (id == null) return BadRequest();
            var result = await _roleService.GetAsync<RoleDto>((Guid)id);
            //TODO ensure ok
            var model = result.Value;
            return View(model);
        }
        
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(RoleDto dto)
        {
            if (!ModelState.IsValid) return View(dto);
            var result = await _roleService.UpdateAsync(dto);
            //TODO Ensure ok
            return RedirectToAction(nameof(Index));
        }

        [HttpGet]
        public async Task<IActionResult> Remove(Guid? id)
        {
            if (id == null) return BadRequest();
            var userRoles = await _roleService.GetByUserAsync((Guid)id);
            //TODO Ensure ok
            var model = new RoleRemoveDto()
            {
                UserId = (Guid)id
            };
            ViewBag.Roles = userRoles.Value;
            return View(model);
        }

        [HttpPost,ValidateAntiForgeryToken]
        public async Task<IActionResult> Remove(Guid id, RoleRemoveDto dto)
        {
            var result = await _roleService.RemoveRolesAsync(dto);
            //Ensure ok
            return RedirectToAction("Index","User");
        }
        
        [HttpGet]
        public async Task<IActionResult> Assign(Guid? id)
        {
            if (id == null) return BadRequest();
            var userRoles = await _roleService.GetByUserAsync((Guid)id);
            var allRoles = await _roleService.GetAllAsync<RoleDto>();
            //TODO Ensure ok
            var model = new RoleAssignDto()
            {
                UserId = (Guid)id,
                Roles = allRoles.Value.Select(x => x.Name).Except(userRoles.Value).ToList(),
                UserRoles = userRoles.Value.ToList()
            };
            return View(model);
        }

        [HttpPost,ValidateAntiForgeryToken]
        public async Task<IActionResult> Assign(Guid id, RoleAssignDto dto)
        {
            var result = await _roleService.AssignRolesAsync(dto);
            //Ensure ok
            return RedirectToAction("Index","User");
        }

        [HttpGet]
        public async Task<IActionResult> Delete(Guid? id)
        {
            if (id == null) return BadRequest();
            var result = await _roleService.GetAsync<RoleDto>((Guid)id);
            //TODO ensure ok
            var model = result.Value;
            return View(model);
        }


        [HttpPost, ActionName("Delete"),ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(Guid id)
        {
            var result = await _roleService.DeleteByIdAsync<RoleDto>(id);
            //TODO Ensure OK
            return RedirectToAction("Index");
        }
    }
}

TTS.Web/Controllers/UserController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using AutoMapper;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using TTS.BLL;
using TTS.BLL.Services;
using TTS.BLL.Services.Abstract;
using TTS.Shared.Models.User;

namespace TTS.Web.Controllers
{  
    [Authorize(Roles = "admin")]
    public class UserController : Controller
    {
        private readonly ILogger<UserController> _logger;
        private readonly IUserService _userService;
        private readonly IMapper _mapper;

        public UserController(ILogger<UserController> logger, IUserService userService, IMapper mapper)
        {
            _logger = logger;
            _userService = userService;
            _mapper = mapper;
        }
        
        [ResponseCache(CacheProfileName = "Default")]
        public async Task<IActionResult> Index()
        {
            var operationStatus = await _userService.GetAllAsync<UserDto>();
            //TODO добавить сюда ensure ok
            return View(operationStatus.Value);
        }

        [ResponseCache(CacheProfileName = "Default"),HttpGet]
        public async Task<IActionResult> Details(Guid? id)
        {
            if (id == null) return BadRequest();
            var result = await _userService.GetAsync<UserDetailsDto>((Guid) id);
            //TODO Ensure OK

            return View(_mapper.Map<UserDetailsDto>(result.Value));
        }

        public IActionResult Create() => View();

        [HttpPost, ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(UserCreateDto dto)
        {
            if (!ModelState.IsValid) return View(dto);
            var result = await _userService.CreateAsync(dto);
            //TODO Ensure OK

            return RedirectToAction(nameof(Index));
        }
        
        [HttpGet]
        public async Task<IActionResult> Edit(Guid? id)
        {
            if (id == null) return BadRequest();
            var result = await _userService.GetAsync<UserEditDto>((Guid)id);
            //TODO Ensure OK
            return View(_mapper.Map<UserEditDto>(result.Value));
        }
        
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(UserEditDto dto)
        {
            if (!ModelState.IsValid) return View(dto);
            var result = await _userService.UpdateAsync(dto);
            //TODO ensure OK
            return RedirectToAction(nameof(Index));
        }
        
        [HttpGet]
        public async Task<IActionResult> Delete(Guid? id)
        {
            if (id == null) return BadRequest();

            var result = await _userService.GetAsync<UserDto>((Guid)id);
            //TODO Ensure OK

            return View(_mapper.Map<UserDto>(result));
        }

        [HttpPost, ActionName("Delete"), ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(Guid id)
        {
            var result = await _userService.DeleteByIdAsync<UserDto>(id);
            //TODO ensure OK
            return RedirectToAction(nameof(Index));
        }
    }
}

TTS.Web/Views/User/Create.cshtml
@model UserCreateDto

@{
    ViewData["Title"] = "Create";
    Layout = "../Shared/_Layout.cshtml";
}

<h1>Create</h1>

<h4>UserViewModel</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Email" class="control-label"></label>
                <input asp-for="Email" class="form-control" />
                <span asp-validation-for="Email" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Password" class="control-label"></label>
                <input asp-for="Password" class="form-control" />
                <span asp-validation-for="Password" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

TTS.Web/Views/User/Delete.cshtml
@model UserDto

@{
    ViewData["Title"] = "Delete";
    Layout = "../Shared/_Layout.cshtml";
}

<h1>Delete</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>UserViewModel</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Email)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Email)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Name)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Name)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.BirthDate)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.BirthDate)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

TTS.Web/Views/User/Details.cshtml
@model UserDetailsDto

@{
    ViewData["Title"] = "Details";
    Layout = "../Shared/_Layout.cshtml";
}

<h1>Details</h1>

<div>
    <h4>UserViewModel</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Email)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Email)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.PhoneNumber)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.PhoneNumber)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.FirstName)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.FirstName)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.LastName)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.LastName)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.SecondName)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.SecondName)
        </dd>
        
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.BirthDate)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.BirthDate)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Position)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Position)
        </dd>
    </dl>
</div>
<div>
    <a asp-action="Edit" asp-route-id="@Model.Id">Edit</a> |
    <a asp-action="Index">Back to List</a>
</div>

TTS.Web/Views/User/Edit.cshtml
@model UserEditDto

@{
    ViewData["Title"] = "Edit";
    Layout = "../Shared/_Layout.cshtml";
}

<h1>Edit</h1>

<h4>EditUserViewModel</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <input type="hidden" asp-for="Id" value="@Model.Id"/>
            </div>
            <div class="form-group">
                <label asp-for="FirstName" class="control-label"></label>
                <input asp-for="FirstName" class="form-control" />
                <span asp-validation-for="FirstName" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="LastName" class="control-label"></label>
                <input asp-for="LastName" class="form-control" />
                <span asp-validation-for="LastName" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="SecondName" class="control-label"></label>
                <input asp-for="SecondName" class="form-control" />
                <span asp-validation-for="SecondName" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Position" class="control-label"></label>
                <input asp-for="Position" class="form-control" />
                <span asp-validation-for="Position" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="BirthDate" class="control-label"></label>
                <input asp-for="BirthDate" class="form-control" />
                <span asp-validation-for="BirthDate" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

TTS.Web/Views/User/Index.cshtml
@using System.Reflection.Metadata
@using Microsoft.AspNetCore.Mvc.RazorPages
@model IEnumerable<UserDto>

@{
    ViewData["Title"] = "Index";
    Layout = "../Shared/_Layout.cshtml";
}

<h1>Index</h1>

<p>
    <a asp-action="Create">Create New</a>
</p>
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Email)
            </th>
            <th>
                Name
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Position)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Age)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Email)
            </td>
            <td>
                @Html.DisplayFor(modelItem=>item.Name)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Position)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Age)
            </td>
            <td>
                <a asp-action="Add" asp-controller="Employee" asp-route-id="@item.Id" class="btn btn-outline-primary">Add Employee</a>
                <a asp-action="Edit" asp-controller="User" asp-route-id="@item.Id" class="btn btn-outline-primary">Edit</a>
                <a asp-action="Assign" asp-controller="Role" asp-route-id="@item.Id" class="btn btn-outline-primary">Assign role</a>
                <a asp-action="Delete" asp-controller="User" asp-route-id="@item.Id" class="btn btn-outline-danger">Delete</a>
                <a asp-action="Details" asp-controller="User" asp-route-id="@item.Id" class="btn btn-outline-primary">Details</a> 
            </td>
        </tr>
}
    </tbody>
</table>

TTS.Web/Views/User/_List.cshtml
@model IEnumerable<UserDto>


    <ejs-grid id="GridUser" dataSource="@Model"  toolbar="@(new List<string>() { "Add", "Edit", "Delete", "Update", "Cancel" })" allowPaging="true">
        <e-grid-editSettings allowAdding="true" allowDeleting="true" allowEditing="true" mode="Dialog"></e-grid-editSettings>
        <e-grid-pagesettings pageCount="5 "></e-grid-pagesettings>
        <e-grid-columns>
            <e-grid-column field="Name" headerText="Name" validationRules="@(new { required=true})" textAlign="Center"  width="200"></e-grid-column>
            <e-grid-column field="Email" headerText="Email"  textAlign="Center"></e-grid-column>
            <e-grid-column field="Position" headerText="Position"  textAlign="Center"></e-grid-column>
            <e-grid-column field="Age" headerText="Age"  textAlign="Center"></e-grid-column>
        </e-grid-columns>
    </ejs-grid>